name: Deploy

on: [push]
#  workflow_run:
#    workflows: ["Run Tests"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Install dependencies
        run: npm ci
      - run: npm deploy
